Run7 Chamber
JPETTomography/J-PET-geant4 pull request #10
Opened 2019-03-12 08:43 UTC by Jchhokar

Addition of Run7 small chamber geometry. Chamber is made from plastic material (polyamide PA6) and in the centre of the chamber there is a filing of XAD4 (thickness 6mm).

2019-03-12 08:43 UTC, JPETTomographyTester commented
Can one of the admins verify this patch?

2019-03-18 14:46 UTC, DariaKisielewska requested changes
General comment: are the implemented dimensions corresponds to the measured ones? 
We already had a bad experiences with technical drawings ...

2019-03-18 14:46 UTC, daria137 commented on src/DetectorConstruction.cc
> +   G4Polycone* smallChamber = new G4Polycone("bigChamber",0*degree,360*degree, 18 , z, rInner, rOuter);
bigChamber name is misleading here

2019-03-18 14:46 UTC, daria137 commented on src/DetectorConstruction.cc
> +   G4Polycone* smallChamber = new G4Polycone("bigChamber",0*degree,360*degree, 18 , z, rInner, rOuter);
also while running code a following exception occurs:

-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : GeomMgt1002
      issued by : G4Polycone::CalculateExtent()
Triangulation of RZ contour has failed for solid: bigChamber !
Extent has been calculated using boundary box
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------

please check if size of rOuter and rInner ... are as they suppose to be

2019-04-18 13:49 UTC, DariaKisielewska requested changes
Runt7 branch should be updated to current develop branch

2019-04-18 13:49 UTC, daria137 commented on src/DetectorConstruction.cc
> +//   G4double z[] = {-8.9*cm, -8.85*cm, -8.8*cm, -7.81*cm, -7.8*cm, -6.61*cm, -6.6*cm, -5.1*cm, -4.9*cm, -3.1*cm, -2.8*cm, 2.8*cm, 3.1*cm, 4.9*cm, 5.1*cm, 6.6*cm, 6.61*cm, 7.8*cm, 7.81*cm, 8.8*cm, 8.
if those values are not needed then please remove them

2019-04-18 13:49 UTC, daria137 commented on src/DetectorConstruction.cc
> +//Jc
please remove commented text

2019-04-18 13:49 UTC, daria137 commented on src/DetectorConstruction.cc
> +//JC
please remove commented text

2019-06-16 09:22 UTC, daria137 commented
Merged by hand

2019-06-16 09:22 UTC, closed without merging