Code formatting
JPETTomography/J-PET-geant4 pull request #15
Opened 2019-06-17 01:02 UTC by kkacprzak

- code formatting with astyle,
- adding doxy headers, similar to those we use in Framework,
- removing redundant commented code and useless comments,
- no functional changes in the code,
- some documentation polishing

2019-06-17 16:20 UTC, DariaKisielewska requested changes
Minor changes requested

2019-06-17 16:20 UTC, DariaKisielewska commented on README.md
> +  `-DGEANT4_USE_QT=ON -DGEANT4_INSTALL_DATA=ON -DGEANT4_USE_OPENGL_X11=ON -DGEANT4_USE_GDML=ON -DGEANT4_BUILD_MULTITHREADED=ON`
Code now is not multi-thread safe. I propose to remove -DGEANT4_BUILD_MULTITHREADED=ON`

2019-06-17 16:20 UTC, DariaKisielewska commented on README.md
> +   - runNr=3/5/6
3/5/6/7

2019-06-17 16:20 UTC, DariaKisielewska commented on README.md
> + - `/jpetmc/detector/loadJPetExtendedGeom`
ready - this flag is loading 4th layer

2019-06-17 16:20 UTC, DariaKisielewska commented on README.md
more paramaters:
/jpetmc/event/save2g  Events with registered 2g will be saved
/jpetmc/event/save3g Events with registered 3g will be saved
/jpetmc/event/printEvtStat Print how many events was generated
/jpetmc/event/printEvtFactor Define X in divisor (10^X) for number of printed event
/jpetmc/event/ShowProgress Print how many events was generated (in %)

/jpetmc/source/nema  Give nema point number to simulate (1-6)

/jpetmc/source/gammaBeam/setEnergy  setPosition setMomentum

/jpetmc/source/isotope/setShape cylinder
/jpetmc/source/isotope/setNGamma  Give number of gamma quanta to generate 1 / 2 / 3 
/jpetmc/source/isotope/setShape/cylinderRadius
/jpetmc/source/isotope/setShape/cylinderZ  For cylindrical shape - set z (half length)
/jpetmc/source/isotope/setPosition  Set position of the source

2019-06-23 23:43 UTC, kkacprzak commented on README.md
> +  `-DGEANT4_USE_QT=ON -DGEANT4_INSTALL_DATA=ON -DGEANT4_USE_OPENGL_X11=ON -DGEANT4_USE_GDML=ON -DGEANT4_BUILD_MULTITHREADED=ON`
ok

2019-06-23 23:44 UTC, kkacprzak commented on README.md
> +   - runNr=3/5/6
ok

2019-06-23 23:45 UTC, kkacprzak commented on README.md
> + - `/jpetmc/detector/loadJPetExtendedGeom`
ok

2019-06-24 01:38 UTC, kkacprzak commented on README.md
I created new file with parameters and moved all of them there

2019-06-24 01:39 UTC, kkacprzak commented
Changes done, ready for next review

2019-06-26 18:49 UTC, DariaKisielewska approved these changes

2019-06-26 18:50 UTC, merged