ModularLayerConfigs
JPETTomography/J-PET-geant4 pull request #21
Opened 2019-07-25 14:48 UTC by pnp-sushil

Modular layers are configured in the latest version of Geant4 package.

2019-07-26 07:58 UTC, DariaKisielewska requested changes
please provide also a messenger that will allow to turn on/off modular layer and/or its components

2019-07-26 07:58 UTC, daria137 commented on Core/DetectorConstruction.cpp
> +  fLoadWrapping(true),fLoadModularLayer(true)
modular layer is an addition to existing setup - flag should be set to false

2019-07-26 07:58 UTC, daria137 commented on Core/DetectorConstruction.cpp
> +  //fLoadModularLayer(false) originally off
please remove comments

2019-07-29 13:15 UTC, kdulski reviewed
I have only small stylish comments:
Maybe try to fit the pattern
Line 341-342   
   " 38.186, 38.192, 38.212, 38.244, 38.289, 38.346, 38.416
  };"
change to 
" 38.186, 38.192, 38.212, 38.244, 38.289, 38.346, 38.416};"
so it looks the definition of other constants

Additionally Line 348
It would be nice to add space after radius_16[13] but before equal sign
and the same treatment to line 353, 361, 362, 364, 365

In line 369 in for loop, so the loop looks like other for`s change 
k = 1 to k=1
and opening of 369 line for loop is not on the same level as the closing of it. It can be misleading if loop will grow.
Try to keep one convention of opening if`s and for`s
Choose from one of the
-> for() {}
-> for() {
-> for()
    {
And to keep nested loop on proper level, eg. loop in line 383 and if in 374.

2019-11-15 10:01 UTC, JPETTomographyTester commented
Found 112 violations:

**Reporter**: cppcheck-raporter
**Rule**: functionConst
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/SourceParams.h L47

Technically the member function &#39;SourceParams::GetGammasNumber&#39; can be const.. The member function &#39;SourceParams::GetGammasNumber&#39; can be made a const function. Making this function &#39;const&#39; should not cause compiler errors. Even though the function can be made const function technically it may not make sense conceptually. Think about your design and the task of the function first - is it a function that must not change object internal state?

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1526075549>*

**Reporter**: cppcheck-raporter
**Rule**: functionConst
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/SourceParams.h L52

Technically the member function &#39;SourceParams::GetShape&#39; can be const.. The member function &#39;SourceParams::GetShape&#39; can be made a const function. Making this function &#39;const&#39; should not cause compiler errors. Even though the function can be made const function technically it may not make sense conceptually. Think about your design and the task of the function first - is it a function that must not change object internal state?

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a507669554>*

**Reporter**: cppcheck-raporter
**Rule**: functionConst
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/SourceParams.h L57

Technically the member function &#39;SourceParams::GetShapeDim&#39; can be const.. The member function &#39;SourceParams::GetShapeDim&#39; can be made a const function. Making this function &#39;const&#39; should not cause compiler errors. Even though the function can be made const function technically it may not make sense conceptually. Think about your design and the task of the function first - is it a function that must not change object internal state?

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1673378271>*

**Reporter**: cppcheck-raporter
**Rule**: functionConst
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/SourceParams.h L62

Technically the member function &#39;SourceParams::GetShapeCenterPosition&#39; can be const.. The member function &#39;SourceParams::GetShapeCenterPosition&#39; can be made a const function. Making this function &#39;const&#39; should not cause compiler errors. Even though the function can be made const function technically it may not make sense conceptually. Think about your design and the task of the function first - is it a function that must not change object internal state?

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1615191380>*

**Reporter**: cppcheck-raporter
**Rule**: functionConst
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/BeamParams.h L39

Technically the member function &#39;BeamParams::GetVtx&#39; can be const.. The member function &#39;BeamParams::GetVtx&#39; can be made a const function. Making this function &#39;const&#39; should not cause compiler errors. Even though the function can be made const function technically it may not make sense conceptually. Think about your design and the task of the function first - is it a function that must not change object internal state?

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-356137783>*

**Reporter**: cppcheck-raporter
**Rule**: functionConst
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/BeamParams.h L43

Technically the member function &#39;BeamParams::GetEne&#39; can be const.. The member function &#39;BeamParams::GetEne&#39; can be made a const function. Making this function &#39;const&#39; should not cause compiler errors. Even though the function can be made const function technically it may not make sense conceptually. Think about your design and the task of the function first - is it a function that must not change object internal state?

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a2055392426>*

**Reporter**: cppcheck-raporter
**Rule**: functionConst
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/BeamParams.h L47

Technically the member function &#39;BeamParams::GetMomentum&#39; can be const.. The member function &#39;BeamParams::GetMomentum&#39; can be made a const function. Making this function &#39;const&#39; should not cause compiler errors. Even though the function can be made const function technically it may not make sense conceptually. Think about your design and the task of the function first - is it a function that must not change object internal state?

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-2112836129>*

**Reporter**: cppcheck-raporter
**Rule**: functionConst
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/BeamParams.h L51

Technically the member function &#39;BeamParams::GetPolarization&#39; can be const.. The member function &#39;BeamParams::GetPolarization&#39; can be made a const function. Making this function &#39;const&#39; should not cause compiler errors. Even though the function can be made const function technically it may not make sense conceptually. Think about your design and the task of the function first - is it a function that must not change object internal state?

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a972652452>*

**Reporter**: cppcheck-raporter
**Rule**: functionConst
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/HistoManager.h L79

Technically the member function &#39;HistoManager::MakeControlHisto&#39; can be const.. The member function &#39;HistoManager::MakeControlHisto&#39; can be made a const function. Making this function &#39;const&#39; should not cause compiler errors. Even though the function can be made const function technically it may not make sense conceptually. Think about your design and the task of the function first - is it a function that must not change object internal state?

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a214013368>*

**Reporter**: cppcheck-raporter
**Rule**: functionConst
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Core/HistoManager.h L86

Technically the member function &#39;HistoManager::GetGeantInfo&#39; can be const.. The member function &#39;HistoManager::GetGeantInfo&#39; can be made a const function. Making this function &#39;const&#39; should not cause compiler errors. Even though the function can be made const function technically it may not make sense conceptually. Think about your design and the task of the function first - is it a function that must not change object internal state?

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1306839399>*

**Reporter**: cppcheck-raporter
**Rule**: noExplicitConstructor
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Info/PrimaryGeneratorActionMessenger.h L35

Class &#39;PrimaryGeneratorActionMessenger&#39; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1454825376>*

**Reporter**: cppcheck-raporter
**Rule**: noExplicitConstructor
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/Actions/PrimaryGenera [...]

2019-12-04 10:30 UTC, kdulski reviewed
PR ok.
Can You just instead editing extendedSource.mac leave it as it was but
create an example macro for 4th layer?

2020-02-05 11:53 UTC, merged