Nema phantom extension
JPETTomography/J-PET-geant4 pull request #67
Opened 2023-02-28 12:44 UTC by kdulski

Added:
- Modular way of creating phantom construction from materials such as water, aluminium, silica, plastic for which teh user can set a density in macro. 
- Various shapes (box, sphere, eliptical cylinder, cylinder) with rotation and translation added. 
-  More complex combination such as union subtraction and intersection of the phantom construction elements 
- Full positronium decay modes for nema points
- Implemented a dummy way to correlate density of the material with the positron reach and lifetime of direct positron-electron annihilation
- Three new histograms density of material in which annihilation occured as a function of X/Y/Z
- Spherical shape of nema point generation

Still can be done:
- general generation of the phantom construction material
- Proper definition of the positron range / direct lifetime as a function of density
- New histograms / fields in TTree : material ID / name in which annihilation took place

2023-02-28 12:46 UTC, JPETTomographyTester commented
Found 9 violations:

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/examples/basic/basic.cc L51

The function &#39;Construct&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-37406236>*

**Reporter**: cppcheck-raporter
**Rule**: redundantAssignment
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/examples/external/external.cc L99

Variable &#39;cone_mesh&#39; is reassigned a value before the old one has been used if variable is no semaphore variable.. Variable &#39;cone_mesh&#39; is reassigned a value before the old one has been used. Make sure that this variable is not used like a semaphore in a threading environment before simplifying this code.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1979725627>*

**Reporter**: cppcheck-raporter
**Rule**: redundantAssignment
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/examples/external/external.cc L93

Variable &#39;cone_mesh&#39; is reassigned a value before the old one has been used if variable is no semaphore variable.. Variable &#39;cone_mesh&#39; is reassigned a value before the old one has been used. Make sure that this variable is not used like a semaphore in a threading environment before simplifying this code.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1541790971>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/src/BuiltInReader.cc L81

The function &#39;BuiltIn&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a229782320>*

**Reporter**: cppcheck-raporter
**Rule**: noExplicitConstructor
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/tests/Simulator.hh L29

Class &#39;DetectorConstruction&#39; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-2004644777>*

**Reporter**: cppcheck-raporter
**Rule**: unreadVariable
**Severity**: INFO
**File**: Core/DetectorConstruction.cpp L1369

Variable &#39;rotationNew&#39; is assigned a value that is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1362421875>*

**Reporter**: cppcheck-raporter
**Rule**: variableScope
**Severity**: INFO
**File**: Core/DetectorConstruction.cpp L1331

The scope of the variable &#39;phantMatExt&#39; can be reduced. Warning: Be careful when fixing this message, especially when there are inner loops. Here is an example where cppcheck will write that the scope for &#39;i&#39; can be reduced:\012void f(int x)\012{\012    int i &#61; 0;\012    if (x) {\012        // it&#39;s safe to move &#39;int i &#61; 0;&#39; here\012        for (int n &#61; 0; n &lt; 10; ++n) {\012            // it is possible but not safe to move &#39;int i &#61; 0;&#39; here\012            do_something(&amp;i);\012        }\012    }\012}\012When you see this message it is always safe to reduce the variable scope 1 level.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a2017539277>*

**Reporter**: cppcheck-raporter
**Rule**: variableScope
**Severity**: INFO
**File**: Core/DetectorConstruction.cpp L1330

The scope of the variable &#39;phantomElementMaterial&#39; can be reduced. Warning: Be careful when fixing this message, especially when there are inner loops. Here is an example where cppcheck will write that the scope for &#39;i&#39; can be reduced:\012void f(int x)\012{\012    int i &#61; 0;\012    if (x) {\012        // it&#39;s safe to move &#39;int i &#61; 0;&#39; here\012        for (int n &#61; 0; n &lt; 10; ++n) {\012            // it is possible but not safe to move &#39;int i &#61; 0;&#39; here\012            do_something(&amp;i);\012        }\012    }\012}\012When you see this message it is always safe to reduce the variable scope 1 level.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1383315618>*

**Reporter**: cppcheck-raporter
**Rule**: unmatchedSuppression
**Severity**: INFO
**File**: Core/DetectorConstruction.cpp L70

Unmatched suppression: unusedFunction

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1999427137>*

 *<ACCUMULATED-VIOLATIONS>*

2023-04-03 12:00 UTC, JPETTomographyTester commented
Found 8 violations:

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/examples/basic/basic.cc L51

The function &#39;Construct&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-37406237>*

**Reporter**: cppcheck-raporter
**Rule**: redundantAssignment
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/examples/external/external.cc L99

Variable &#39;cone_mesh&#39; is reassigned a value before the old one has been used if variable is no semaphore variable.. Variable &#39;cone_mesh&#39; is reassigned a value before the old one has been used. Make sure that this variable is not used like a semaphore in a threading environment before simplifying this code.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1979725627>*

**Reporter**: cppcheck-raporter
**Rule**: redundantAssignment
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/examples/external/external.cc L93

Variable &#39;cone_mesh&#39; is reassigned a value before the old one has been used if variable is no semaphore variable.. Variable &#39;cone_mesh&#39; is reassigned a value before the old one has been used. Make sure that this variable is not used like a semaphore in a threading environment before simplifying this code.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1541790971>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/src/BuiltInReader.cc L81

The function &#39;BuiltIn&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a229782319>*

**Reporter**: cppcheck-raporter
**Rule**: noExplicitConstructor
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/tests/Simulator.hh L29

Class &#39;DetectorConstruction&#39; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-2004644777>*

**Reporter**: cppcheck-raporter
**Rule**: unreadVariable
**Severity**: INFO
**File**: Core/DetectorConstruction.cpp L1369

Variable &#39;rotationNew&#39; is assigned a value that is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-1362421876>*

**Reporter**: cppcheck-raporter
**Rule**: variableScope
**Severity**: INFO
**File**: Core/DetectorConstruction.cpp L1331

The scope of the variable &#39;phantMatExt&#39; can be reduced. Warning: Be careful when fixing this message, especially when there are inner loops. Here is an example where cppcheck will write that the scope for &#39;i&#39; can be reduced:\012void f(int x)\012{\012    int i &#61; 0;\012    if (x) {\012        // it&#39;s safe to move &#39;int i &#61; 0;&#39; here\012        for (int n &#61; 0; n &lt; 10; ++n) {\012            // it is possible but not safe to move &#39;int i &#61; 0;&#39; here\012            do_something(&amp;i);\012        }\012    }\012}\012When you see this message it is always safe to reduce the variable scope 1 level.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a2017539276>*

**Reporter**: cppcheck-raporter
**Rule**: unmatchedSuppression
**Severity**: INFO
**File**: Core/DetectorConstruction.cpp L70

Unmatched suppression: unusedFunction

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1999427136>*

 *<ACCUMULATED-VIOLATIONS>*

2023-04-04 12:07 UTC, kkacprzak requested changes
A great amount of job introducing the shapes, materials, generation modes etc.! All looks clear and straightforward. 

There is one point with the rotation vectors, that can be somewhat improved.
Also, please comment more on the usage of the probability functions for the positron path and consider moving the constants into the constants class.

2023-04-04 12:07 UTC, kkacprzak commented on Actions/PrimaryGeneratorAction.cpp
> +  } else if (mode == PositroniumDecayMode::oPs) {
To keep it consistent, the function's name should be updated to `fNemaGenerator.SetPointOPsLifetime(nemaPoint, lifetime);`

2023-04-04 12:07 UTC, kkacprzak commented on Core/DetectorConstruction.h
> +  std::vector<PhantElem> phantomElements;
I suggest following the convention and renaming these private members to `fPhantomElements` and `fPhantomElemIDs`

2023-04-04 12:07 UTC, kkacprzak commented on Core/DetectorConstruction.cpp
> +        if (phantomElements.at(i).fRotation.size() > 2)
If the `fRotation` was initiated correctly, then its size is always equal to 3, the three condition statements can be removed.

2023-04-04 12:07 UTC, kkacprzak commented on Core/DetectorConstruction.cpp
> +              rotMatNew->rotateZ(phantomElements.at(idPhantElem.at(idToCombine)).fRotation.at(2)*deg);
The rotation vector should always have the size == 3, why these checks are necessary?

2023-04-04 12:07 UTC, kkacprzak commented on Core/DetectorConstruction.cpp
> +          G4Element* elC = new G4Element("Carbon", "C", z=6., a=12.0107*g/mole);
Please avoid hard-coded values and use defined constants.

2023-04-04 12:07 UTC, kkacprzak commented on Core/PrimaryGenerator.cpp
> +    reach = 19.378*std::pow(density, -1.53977); // test function of reach (in mm)
Please define the constants used in this function and comment on their values

2023-04-04 12:07 UTC, kkacprzak commented on Core/PrimaryGenerator.cpp
> +    DirectLF = 0.819151*exp(-0.517436*density);   //dummy function for test in ns
What are the constants in this function and can they be changed by the user?

2023-04-04 12:07 UTC, kkacprzak commented on Core/PrimaryGeneratorConstants.h
> +  static const G4double DIRECT_PS_ANNIHILATION = 0.6;
Please add a short comment about these constants, where are they used and that they are not in the cosmic muon section

2024-02-01 15:34 UTC, JPETTomographyTester commented
Found 8 violations:

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/examples/basic/basic.cc L51

The function &#39;Construct&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-37406237>*

**Reporter**: cppcheck-raporter
**Rule**: redundantAssignment
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/examples/external/external.cc L99

Variable &#39;cone_mesh&#39; is reassigned a value before the old one has been used if variable is no semaphore variable.. Variable &#39;cone_mesh&#39; is reassigned a value before the old one has been used. Make sure that this variable is not used like a semaphore in a threading environment before simplifying this code.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1979725627>*

**Reporter**: cppcheck-raporter
**Rule**: redundantAssignment
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/examples/external/external.cc L93

Variable &#39;cone_mesh&#39; is reassigned a value before the old one has been used if variable is no semaphore variable.. Variable &#39;cone_mesh&#39; is reassigned a value before the old one has been used. Make sure that this variable is not used like a semaphore in a threading environment before simplifying this code.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1541790971>*

**Reporter**: cppcheck-raporter
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/src/BuiltInReader.cc L81

The function &#39;BuiltIn&#39; is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a229782319>*

**Reporter**: cppcheck-raporter
**Rule**: noExplicitConstructor
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-geant-4-PRs-root-6/CADMesh/tests/Simulator.hh L29

Class &#39;DetectorConstruction&#39; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-2004644777>*

**Reporter**: cppcheck-raporter
**Rule**: unreadVariable
**Severity**: INFO
**File**: Core/DetectorConstruction.cpp L1368

Variable &#39;rotationNew&#39; is assigned a value that is never used.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1966920650>*

**Reporter**: cppcheck-raporter
**Rule**: variableScope
**Severity**: INFO
**File**: Core/DetectorConstruction.cpp L1332

The scope of the variable &#39;phantMatExt&#39; can be reduced. Warning: Be careful when fixing this message, especially when there are inner loops. Here is an example where cppcheck will write that the scope for &#39;i&#39; can be reduced:\012void f(int x)\012{\012    int i &#61; 0;\012    if (x) {\012        // it&#39;s safe to move &#39;int i &#61; 0;&#39; here\012        for (int n &#61; 0; n &lt; 10; ++n) {\012            // it is possible but not safe to move &#39;int i &#61; 0;&#39; here\012            do_something(&amp;i);\012        }\012    }\012}\012When you see this message it is always safe to reduce the variable scope 1 level.

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-778780786>*

**Reporter**: cppcheck-raporter
**Rule**: unmatchedSuppression
**Severity**: INFO
**File**: Core/DetectorConstruction.cpp L71

Unmatched suppression: unusedFunction

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a539693954>*

 *<ACCUMULATED-VIOLATIONS>*

2024-11-25 17:43 UTC, kkacprzak approved these changes

2024-11-26 15:48 UTC, merged