Code revision & new geometries (run6, nema)
JPETTomography/J-PET-geant4 pull request #8
Opened 2018-11-11 10:31 UTC by daria137

-added control histograms
-added run6 geometry
-added nema simulations
-fixed minor errors
-added request made on Framework meeting

2019-02-11 14:09 UTC, alekgajos requested changes
I have one major concern - in the methods constructing the sources, there is a lot of hard-coded values. Is is not completely unrealistic that we will need to tweak these values in the future for a better match between data and MC and after some time it may not be clear which value is which dimension etc.

I agree that there is no point in making all these values parameters controlled by the user, but I think it would be good to at least define each of them as a constant at the beginning of the `ConstructTarget*` methods and then only use these  constants and not ad-hoc values in the futrher code.
Something like:

```c++
void DetectorConstruction::ConstructTargetRun6()
{
const double chamber_radius = 12.*cm;
const double chamber_outer_radius = chamber_radius + 0.5*cm;
...
```

2019-02-11 14:09 UTC, alekgajos commented on src/DetectorConstruction.cpp
> +   G4double z[] =      {-31.0*cm, -29.0*cm, -28.9*cm, -28*cm, -27.9*cm, 27.9*cm, 28*cm, 28.9*cm, 29*cm,  31*cm };
This is a lot of hard-coding. Could you add an extensive Doxygen-style comment at the top of the `ConstructTargetRun6` method describing the structure of these arrays (meaning of particular elements)?

2019-02-11 14:09 UTC, alekgajos commented on src/DetectorConstruction.cpp
> +   G4LogicalVolume * bigChamber_logical = new G4LogicalVolume(bigChamber, bigChamberRun3Material, "bigChamber_logical");
Perhaps it would be better to name the materials after their real-life components or properties. Names like `bigChamberRun4Material` do not say much about what it is.

2019-02-11 14:09 UTC, alekgajos commented on src/HistoManager.cpp
> +      fHisto[0] = new TH1F("gen_gamma_multiplicity","Generated gammas multiplicity",10,0,10);
inconsistent indentation

2019-02-11 14:09 UTC, alekgajos commented on src/PrimaryGenerator.cpp
>      //printf(" ======================================= \n");
remove commented code

2019-02-11 14:09 UTC, alekgajos commented on src/PrimaryGenerator.cpp
> +      polarization2 = polarization2.rotate( twopi/4.0, gammaMom);
why `twopi/4.0` and not `pi/2.0`?

2019-03-25 13:15 UTC, alekgajos approved these changes

2019-03-25 13:17 UTC, wkrzemien commented on include/DetectorConstruction.h
> +    //// create target used in run5 - small chamber + XAD material inside in a sandwitch form
Sandwich  :-) ?

2019-03-25 13:21 UTC, wkrzemien commented on src/PrimaryGeneratorActionMessenger.cpp
> +    //delete fGammaBeamSetPolarization;
to remove

2019-03-25 13:21 UTC, wkrzemien commented on src/PrimaryGeneratorActionMessenger.cpp
> +//    fGammaBeamSetPolarization = new G4UIcmdWith3Vector("/jpetmc/source/gammaBeam/setPolarization",this);
those as well

2019-03-25 13:22 UTC, wkrzemien commented on src/PrimaryGeneratorActionMessenger.cpp
> +//    fGammaBeamSetPolarization = new G4UIcmdWith3Vector("/jpetmc/source/gammaBeam/setPolarization",this);
I mean it is better to remove the commented code

2019-03-25 13:22 UTC, wkrzemien commented on src/PrimaryGenerator.cpp
> +      // code from Nikodem
I would remove this line as well.

2019-03-25 13:23 UTC, wkrzemien commented on include/PrimaryGeneratorActionMessenger.h
> +        //G4UIcmdWith3Vector* fGammaBeamSetPolarization; ///< not implemented !
so maybe remove it?
Or you keep it for some purpose?

2019-03-25 13:26 UTC, wkrzemien commented on include/PrimaryGeneratorAction.h
> +        G4int fNemaPoint;
for the field definitions inside classes you could assign some default values. Otherewise if one forgets to set it , it will still get some  random value, which is hard to track normally/.
I would do something like:

`fBeam= nullptr;
fIsotope = nullptr;
fNeamPoint = -1;`
etc

2019-04-16 11:00 UTC, merged

2019-04-16 11:02 UTC, daria137 commented
Positive reviews - merging commits